python3 train.py \
--train_config ./config.yaml \
--model_config ./models/config.yaml \
--data_config ./data/config.yaml \
--device cpu \
--pickle_path ./data/pickl/audio.pkl \
--store_model_path ./model_store \
--load_model_path ./model_store \
--summary_steps 20 \
--save_steps 20 \
--iterations 100\
